image: ruby:2.6
services:
  - mysql:5.7
variables:
  MYSQL_ROOT_PASSWORD: root
cache:
  paths:
    - vendor/bundle
before_script:
  - ruby -v
  - bundle install --quiet --path vendor/bundle
stages:
  - test
rspec:
  stage: test
  only: ['pushes']
  script:
    - rails db:create RAILS_ENV=test
    - rails db:migrate RAILS_ENV=test
    - bundle exec rspec
