version: '3'
services:
  rails: &rails
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
      - "bundle:/usr/local/bundle"
    ports:
      - "9000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql: &mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "mysql-data:/var/lib/mysql"
    ports:
      - "9906:3306"
volumes:
  mysql-data:
  bundle:
