version: '3'
services:
  rails: &rails
    build:
      context: .
      dockerfile: "Dockerfile.development"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
      - "bundle:/usr/local/bundle"
    ports:
      - "9000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  db: &db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "9906:3306"
volumes:
  db-data:
  bundle: